/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comparc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int rd, rs, rt;
    int opcode;
    int pc = 0;
    int pcTarget = -1;
    boolean check = false;
    boolean proceed = true;
    String instruction, labeladdress;
    String rdbin, rsbin, rtbin, opcodebin, temp = "", offsetbin, addressbin;
    String jumpTo;
    String pcBin;
    int func = 0;
    String addbin = "", funcbin;
    String addresshex = "";

    // regex
    Pattern p = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
    Pattern immediate = Pattern.compile("[^a-f0-9]", Pattern.CASE_INSENSITIVE);
    Matcher m;

    ArrayList<String> labellist = new ArrayList<String>();
    ArrayList<String> opcodelist = new ArrayList<String>();
    ArrayList<String> pclist = new ArrayList<String>();
    ArrayList<String> instructionlist = new ArrayList<String>();

    public NewJFrame() {
        initComponents();
    }

    public void generateOpcode(ArrayList<String> pclist, ArrayList<String> instructionlist) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox9 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(545, 665));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel1.setText("RD");

        jLabel2.setText("RS");

        jLabel3.setText("RT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox4, 0, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, 53, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, 0, 51, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3.add(jPanel4, "card2");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel9.setText("RS");

        jLabel10.setText("RT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jComboBox5))
                .addGap(27, 27, 27))
        );

        jPanel3.add(jPanel5, "card2");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel4.setText("Label");

        jLabel11.setText("RS");

        jLabel13.setText("RT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jComboBox8)
                        .addGap(2, 2, 2)))
                .addGap(25, 25, 25))
        );

        jPanel3.add(jPanel6, "card2");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel5.setText("Offset");

        jLabel14.setText("RD");

        jLabel15.setText("RS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox10, 0, 77, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jComboBox9))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, "card2");

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel6.setText("immediate");

        jLabel16.setText("RD");

        jLabel17.setText("RS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField3)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jPanel3.add(jPanel8, "card2");

        jLabel7.setText("Label");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel9, "card2");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DSUBU", "DDIV", "AND", "DSRLV", "SLT", "BEQ", "LW", "LWU", "SW", "DADDIU", "ORI", "J" }));
        jComboBox1.setName("inst"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Label (optional)");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel22.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Opcode");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setText("Instructions");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        instruction = jComboBox1.getSelectedItem().toString();

        //removing panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        if (instruction.matches("DSUBU") || instruction.matches("AND")
                || instruction.matches("DSRLV") || instruction.matches("SLT")) {
            jPanel3.add(jPanel4);
            jPanel3.repaint();
            jPanel3.revalidate();

        } else if (instruction.matches("DDIV")) {
            jPanel3.add(jPanel5);
            jPanel3.repaint();
            jPanel3.revalidate();

        } else if (instruction.matches("BEQ")) {
            jPanel3.add(jPanel6);
            jPanel3.repaint();
            jPanel3.revalidate();

        } else if (instruction.matches("LW") || instruction.matches("LWU") || instruction.matches("SW")) {
            jPanel3.add(jPanel7);
            jPanel3.repaint();
            jPanel3.revalidate();

        } else if (instruction.matches("DADDIU") || instruction.matches("ORI")) {
            jPanel3.add(jPanel8);
            jPanel3.repaint();
            jPanel3.revalidate();

        } else if (instruction.matches("J")) {
            jPanel3.add(jPanel9);
            jPanel3.repaint();
            jPanel3.revalidate();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void reset() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
        jComboBox10.setSelectedIndex(0);
        jComboBox11.setSelectedIndex(0);
        jComboBox12.setSelectedIndex(0);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        instruction = jComboBox1.getSelectedItem().toString();

        //special character checking upon add
        labeladdress = jTextField5.getText();
        labeladdress.toUpperCase();
        m = p.matcher(labeladdress);
        if (labeladdress.matches("")) {
            labeladdress = "NO LABEL";
            proceed = true;
        } else if (labeladdress.matches("DSUBU") || labeladdress.matches("AND") || labeladdress.matches("DSRLV")
                || labeladdress.matches("SLT") || labeladdress.matches("DDIV") || labeladdress.matches("BEQ")
                || labeladdress.matches("LW") || labeladdress.matches("LWU") || labeladdress.matches("SW")
                || labeladdress.matches("DADDIU") || labeladdress.matches("ORI") || labeladdress.matches("J")) {
            proceed = false;
        } else {

            if (m.find()) { //check for special characters
                proceed = false;
            } else {
                proceed = true;

                for (int i = 0; i < pclist.size(); i++) { //check if label exists
                    if (labellist.get(i).matches(labeladdress)) {
                        proceed = false;
                    }
                }
            }
        }

        if (proceed) {
            if (instruction.matches("DSUBU") || instruction.matches("DDIV") || instruction.matches("AND")
                    || instruction.matches("DSRLV") || instruction.matches("SLT")) {

                //increment pc by 4
                pc = pc + 4;
                pclist.add(Integer.toHexString(pc));

                if (instruction.matches("DDIV")) {
                    rs = jComboBox5.getSelectedIndex();
                    rt = jComboBox6.getSelectedIndex();
                } else {
                    rd = jComboBox4.getSelectedIndex();
                    rs = jComboBox2.getSelectedIndex();
                    rt = jComboBox3.getSelectedIndex();
                }

                //opcode binary
                opcodebin = "000000";

                //rs binary
                rsbin = Integer.toBinaryString(rs);
                if (rsbin.length() != 5) {
                    for (int i = 0; i < 5 - rsbin.length(); i++) {
                        temp = temp + "0";
                    }
                }
                rsbin = temp + rsbin;

                //rt binary
                temp = "";
                rtbin = Integer.toBinaryString(rt);
                if (rtbin.length() != 5) {
                    for (int i = 0; i < 5 - rtbin.length(); i++) {
                        temp = temp + "0";
                    }
                }
                rtbin = temp + rtbin;

                //rd binary
                if (instruction.matches("DDIV")) {
                    rdbin = "00000";
                } else {
                    temp = "";
                    rdbin = Integer.toBinaryString(rd);
                    if (rdbin.length() != 5) {
                        for (int i = 0; i < 5 - rdbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    rdbin = temp + rdbin;
                }

                //additional 5 bits
                addbin = "00000";

                //function
                if (instruction.matches("DSUBU")) {
                    func = 47;
                } else if (instruction.matches("DDIV")) {
                    func = 30;
                } else if (instruction.matches("AND")) {
                    func = 36;
                } else if (instruction.matches("DSRLV")) {
                    func = 22;
                } else if (instruction.matches("SLT")) {
                    func = 42;
                }
                funcbin = Integer.toBinaryString(func);
                if (funcbin.length() != 6) {
                    temp = "";
                    if (funcbin.length() != 6) {
                        for (int i = 0; i < 6 - funcbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    funcbin = temp + funcbin;
                }

                //address in binary
                addressbin = opcodebin + rsbin + rtbin + rdbin + addbin + funcbin;

                //convert to hex
                addresshex = new BigInteger(addressbin, 2).toString(16);
                if (addresshex.length() != 8) {
                    temp = "";
                    for (int i = 0; i < 8 - addresshex.length(); i++) {
                        temp = temp + "0";
                    }
                    addresshex = temp + addresshex;
                }

                opcodelist.add(addresshex);
                labellist.add(labeladdress);

                if (instruction.matches("DDIV")) {
                    instructionlist.add(instruction + " R" + rs + ", R" + rt);
                    if (labeladdress.matches("NO LABEL")) {
                        jLabel21.setText(jLabel21.getText() + '\n' + instruction + " R" + rs + ", R" + rt);
                    } else {
                        jLabel21.setText(jLabel21.getText() + '\n' + labeladdress + ": " + instruction + " R" + rs + ", R" + rt);
                    }
                } else {
                    instructionlist.add(instruction + " R" + rd + ", R" + rs + ", R" + rt);
                    if (labeladdress.matches("NO LABEL")) {
                        jLabel21.setText(jLabel21.getText() + '\n' + instruction + " R" + rd + ", R" + rs + ", R" + rt);
                    } else {
                        jLabel21.setText(jLabel21.getText() + '\n' + labeladdress + ": " + instruction + " R" + rd + ", R" + rs + ", R" + rt);
                    }
                }
                jLabel23.setText("Successfully added!");
            } else if (instruction.matches("BEQ")) {
                if (jTextField1.getText().matches("")) { //special characters or null
                    //error message
                    jLabel23.setText("Invalid Label");
                } else if (jTextField1.getText().matches("DSUBU") || jTextField1.getText().matches("AND") || jTextField1.getText().matches("DSRLV")
                        || jTextField1.getText().matches("SLT") || jTextField1.getText().matches("DDIV") || jTextField1.getText().matches("BEQ")
                        || jTextField1.getText().matches("LW") || jTextField1.getText().matches("LWU") || jTextField1.getText().matches("SW")
                        || jTextField1.getText().matches("DADDIU") || jTextField1.getText().matches("ORI") || jTextField1.getText().matches("J")) {
                    jLabel23.setText("Invalid Label");
                } else {
                    //increment pc by 4
                    pc = pc + 4;
                    pclist.add(Integer.toHexString(pc));

                    rs = jComboBox7.getSelectedIndex();
                    rt = jComboBox8.getSelectedIndex();

                    opcodebin = "000100";

                    //rs binary
                    temp = "";
                    rsbin = Integer.toBinaryString(rs);
                    if (rsbin.length() != 5) {
                        for (int i = 0; i < 5 - rsbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    rsbin = temp + rsbin;

                    //rt binary
                    temp = "";
                    rtbin = Integer.toBinaryString(rt);
                    if (rtbin.length() != 5) {
                        for (int i = 0; i < 5 - rtbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    rtbin = temp + rtbin;

                    addressbin = opcodebin + rsbin + rtbin;
                    //offset

                    /*
                     jumpTo = jTextField1.getText();
                     //address binary

                     instructionlist.add(instruction + " R" + jComboBox7.getSelectedItem() + ", R" + jComboBox8.getSelectedItem() + " ," + jTextField1.getText().toUpperCase());
                     opcodelist.add(addresshex);

                     for (int i = 0; i < pclist.size(); i++) {
                     if (labellist.get(i).matches(labeladdress)) {
                     break;
                     }
                     }

                     opcodelist.add(addresshex);
                     */
                    instructionlist.add(instruction + " R" + jComboBox7.getSelectedItem() + ", R" + jComboBox8.getSelectedItem() + ", " + jTextField1.getText().toUpperCase());
                    if (labeladdress.matches("NO LABEL")) {
                        jLabel21.setText(jLabel21.getText() + instruction + " R" + jComboBox7.getSelectedItem() + ", R" + jComboBox8.getSelectedItem() + ", " + jTextField1.getText().toUpperCase());
                    } else {
                        jLabel21.setText(jLabel21.getText() + labeladdress + ": " + instruction + " R" + jComboBox7.getSelectedItem() + ", R" + jComboBox8.getSelectedItem() + ", " + jTextField1.getText().toUpperCase());
                    }
                    opcodelist.add(addressbin);
                    labellist.add(labeladdress);
                    jLabel23.setText("Successfully added!");
                }

            } else if (instruction.matches("LW") || instruction.matches("LWU") || instruction.matches("SW")) {
                if (jTextField2.getText().matches("") && jTextField2.getText().length() != 4) { //error message special characters and letters g-z
                    jLabel23.setText("Invalid Offset");
                } else {
                    rd = jComboBox9.getSelectedIndex();
                    rs = jComboBox10.getSelectedIndex();

                    //increment pc by 4
                    pc = pc + 4;
                    pclist.add(Integer.toHexString(pc));

                    //opcode binary
                    if (instruction.matches("LW")) {
                        opcode = 35;
                    } else if (instruction.matches("LWU")) {
                        opcode = 39;
                    } else if (instruction.matches("SW")) {
                        opcode = 43;
                    }

                    opcodebin = Integer.toBinaryString(opcode);
                    if (opcodebin.length() != 6) {
                        temp = "";
                        for (int i = 0; i < 6 - opcodebin.length(); i++) {
                            temp = temp + "0";
                        }
                        opcodebin = temp + opcodebin;
                    }

                    //rd binary
                    temp = "";
                    rdbin = Integer.toBinaryString(rd);
                    if (rdbin.length() != 5) {
                        for (int i = 0; i < 5 - rdbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    rdbin = temp + rdbin;

                    //rs binary
                    rsbin = Integer.toBinaryString(rs);
                    if (rsbin.length() != 5) {
                        for (int i = 0; i < 5 - rsbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    rsbin = temp + rsbin;

                    offsetbin = Integer.toBinaryString(Integer.parseInt(jTextField2.getText(), 16));

                    temp = "";
                    if (offsetbin.length() != 16) {
                        for (int i = 0; i < 16 - offsetbin.length(); i++) {
                            temp = temp + "0";
                        }
                    }
                    offsetbin = temp + offsetbin;

                    //address in binary
                    addressbin = opcodebin + rsbin + rdbin + offsetbin;

                    addresshex = new BigInteger(addressbin, 2).toString(16);
                    if (addresshex.length() != 8) {
                        temp = "";
                        for (int i = 0; i < 8 - addresshex.length(); i++) {
                            temp = temp + "0";
                        }
                        addresshex = temp + addresshex;
                    }

                    opcodelist.add(addresshex);

                    instructionlist.add(instruction + " R" + jComboBox9.getSelectedItem() + ", " + jTextField2.getText() + "(R" + jComboBox10.getSelectedItem() + ")");
                    labellist.add(labeladdress);

                    if (labeladdress.matches("NO LABEL")) {
                        jLabel21.setText(jLabel21.getText() + instruction + " R" + jComboBox9.getSelectedItem() + ", " + jTextField2.getText() + "(R" + jComboBox10.getSelectedItem() + ")");
                    } else {
                        jLabel21.setText(jLabel21.getText() + labeladdress + ": " + instruction + " R" + jComboBox9.getSelectedItem() + ", " + jTextField2.getText() + "(R" + jComboBox10.getSelectedItem() + ")");
                    }

                    jLabel23.setText("Successfully added!");
                }

            } else if (instruction.matches("DADDIU") || instruction.matches("ORI")) {
                if (jTextField3.getText().matches("") || jTextField3.getText().length() != 4) {
                    jLabel18.setText("Invalid Offset.");
                } else {

                    String immediateTemp = jTextField3.getText();
                    m = immediate.matcher(immediateTemp);

                    if (!m.find()) {
                        rd = jComboBox11.getSelectedIndex();
                        rs = jComboBox12.getSelectedIndex();

                        //increment pc by 4
                        pc = pc + 4;
                        pclist.add(Integer.toHexString(pc));

                        if (instruction.matches("DADDIU")) {
                            opcode = 25;
                        } else if (instruction.matches("ORI")) {
                            opcode = 13;
                        }

                        opcodebin = Integer.toBinaryString(opcode);
                        if (opcodebin.length() != 6) {
                            temp = "";
                            for (int i = 0; i < 6 - opcodebin.length(); i++) {
                                temp = temp + "0";
                            }
                            opcodebin = temp + opcodebin;
                        }

                        //rs binary
                        temp = "";
                        rsbin = Integer.toBinaryString(rs);
                        if (rsbin.length() != 5) {
                            for (int i = 0; i < 5 - rsbin.length(); i++) {
                                temp = temp + "0";
                            }
                        }
                        rsbin = temp + rsbin;

                        //rd binary
                        temp = "";
                        rdbin = Integer.toBinaryString(rd);
                        if (rdbin.length() != 5) {
                            for (int i = 0; i < 5 - rdbin.length(); i++) {
                                temp = temp + "0";
                            }
                        }
                        rdbin = temp + rdbin;

                        offsetbin = Integer.toBinaryString(Integer.parseInt(jTextField3.getText(), 16));

                        temp = "";
                        if (offsetbin.length() != 16) {
                            for (int i = 0; i < 16 - offsetbin.length(); i++) {
                                temp = temp + "0";
                            }
                        }
                        offsetbin = temp + offsetbin;

                        //address in binary
                        addressbin = opcodebin + rsbin + rdbin + offsetbin;

                        //address in hex
                        addresshex = new BigInteger(addressbin, 2).toString(16);
                        if (addresshex.length() != 8) {
                            temp = "";
                            for (int i = 0; i < 8 - addresshex.length(); i++) {
                                temp = temp + "0";
                            }
                            addresshex = temp + addresshex;
                        }

                        instructionlist.add(instruction + " R" + jComboBox11.getSelectedItem() + ", R" + jComboBox12.getSelectedItem() + ", #" + jTextField3.getText());

                        if (labeladdress.matches("NO LABEL")) {
                            jLabel21.setText(jLabel21.getText() + instruction + " R" + jComboBox11.getSelectedItem() + ", R" + jComboBox12.getSelectedItem() + ", #" + jTextField3.getText());
                        } else {
                            jLabel21.setText(jLabel21.getText() + labeladdress + ": " + instruction + " R" + jComboBox11.getSelectedItem() + ", R" + jComboBox12.getSelectedItem() + ", #" + jTextField3.getText());
                        }

                        opcodelist.add(addresshex);
                        labellist.add(labeladdress);
                    } else {
                        jLabel23.setText("Invalid immediate value");
                    }
                }

            } else if (instruction.matches("J")) {
                if (jTextField4.getText().matches("")) { //special characters
                    jLabel18.setText("Invalid Offset");
                } else {

                    //increment pc by 4
                    pc = pc + 4;
                    pclist.add(Integer.toHexString(pc));

                    opcodebin = "000010";

                    /*
                     String jumpTo = jTextField4.getText().toUpperCase();
                     System.out.println(jumpTo);
                     for (int i = 0; i < labellist.size(); i++) {
                     if (labellist.get(i).contains(jumpTo)) {
                     pcTarget = Integer.valueOf(pclist.get(i)); // actual pc of label - current pc
                     break;
                     } else {
                     pcTarget = -1;
                     System.out.println(labellist.get(i));
                     }
                     }
                     if (pcTarget != -1) {
                     pcBin = Integer.toBinaryString(pcTarget);
                     System.out.println("PCTarget: " + pcBin);

                     addressbin = opcodebin + rsbin + rtbin + pcBin;

                     //address in hex
                     addresshex = new BigInteger(addressbin, 2).toString(16);
                     if (addresshex.length() != 8) {
                     temp = "";
                     for (int i = 0; i < 8 - addresshex.length(); i++) {
                     temp = temp + "0";
                     }
                     addresshex = temp + addresshex;
                     //String jumpTo = jTextField1.getText();
                     //address in binary
                     addressbin = opcodebin + rsbin + rtbin;
                     }

                     instructionlist.add(instruction + " " + jTextField4.getText().toUpperCase());
                     opcodelist.add(addresshex);
                     } else {
                     instructionlist.add(instruction + " " + jTextField4.getText().toUpperCase());
                     addresshex = "0000";
                     opcodelist.add(addresshex);
                     }
                     */
                    instructionlist.add(instruction + " " + jTextField4.getText().toUpperCase());

                    if (labeladdress.matches("NO LABEL")) {
                        jLabel21.setText(jLabel21.getText() + instruction + " " + jTextField4.getText().toUpperCase());
                    } else {
                        jLabel21.setText(jLabel21.getText() + labeladdress + ": " + instruction + " " + jTextField4.getText().toUpperCase());
                    }
                    opcodelist.add(opcodebin);
                    labellist.add(labeladdress);
                }

            }
        } else {
            jLabel23.setText("Invalid label");
        }

        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        labeladdress = jTextField5.getText();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        boolean proceed = true;
        int i, j, x, offset;
        String label;
        for (i = 0; i < pclist.size(); i++) {
            if (instructionlist.get(i).contains("BEQ")) {
                label = instructionlist.get(i).substring(instructionlist.get(i).lastIndexOf(", ") + 2);
                for (j = 0; j < labellist.size(); j++) {
                    if (labellist.get(j).matches(label)) {
                        break;
                    }
                }
                if (j == labellist.size()) {
                    proceed = false;
                } else { //label above
                    offset = j - (i + 1);
                    offsetbin = Integer.toBinaryString(offset);

                    if (offsetbin.length() > 16) {
                        offsetbin = offsetbin.substring(16);
                    } else {
                        temp = "";
                        for (x = 0; x < 16 - offsetbin.length(); x++) {
                            temp = temp + "0";
                        }
                        offsetbin = temp + offsetbin;
                    }
                    offsetbin = opcodelist.get(i) + offsetbin;
                    addresshex = new BigInteger(offsetbin, 2).toString(16);
                    if (addresshex.length() != 8) {
                        temp = "";
                        for (int m = 0; m < 8 - addresshex.length(); m++) {
                            temp = temp + "0";
                        }
                        addresshex = temp + addresshex;
                    }
                    opcodelist.set(i, addresshex);
                }
            } else if (instructionlist.get(i).contains("J")) {
                int ctr = 0;
                label = instructionlist.get(i).substring(2);
                for (j = 0; j < labellist.size(); j++) {
                    if (labellist.get(j).matches(label)) {
                        break;
                    }
                }
                if (j == labellist.size()) {
                    proceed = false;
                } else {
                    ctr = j;
                    offsetbin = Integer.toBinaryString(ctr);
                    if (offsetbin.length() != 26) {
                        temp = "";
                        for (x = 0; x < 26 - offsetbin.length(); x++) {
                            temp = temp + "0";
                        }
                        offsetbin = temp + offsetbin;
                    }
                    offsetbin = opcodelist.get(i) + offsetbin;

                    addresshex = new BigInteger(offsetbin, 2).toString(16);
                    if (addresshex.length() != 8) {
                        temp = "";
                        for (int m = 0; m < 8 - addresshex.length(); m++) {
                            temp = temp + "0";
                        }
                        addresshex = temp + addresshex;
                    }
                    opcodelist.set(i, addresshex);
                }
            }
        }
        
        if(proceed) {
            for(i=0; i<pclist.size(); i++) {
                jLabel18.setText(jLabel18.getText() + opcodelist.get(i));
            }
        } else {
            System.out.println("ERROR");
        }
        /*
         int temppc;
         boolean jump = false;
         String rstemp, rttemp;
         for (int i = 0; i < opcodelist.size(); i++) {
         if (opcodelist.get(i).matches("0000")) {
         System.out.println("NAKITA NA PO");
         for (int j = 0; j < labellist.size(); j++) {
         if (instructionlist.get(i).contains(labellist.get(j))) { // nakita na saan magjump
         System.out.println(labellist.get(j));
         temppc = Integer.valueOf(pclist.get(i));

         if (instructionlist.get(i).startsWith("J")) {
         opcode = 2;
         rs = 0;
         rt = 0;
         jump = true;
         } else { //beq
         opcode = 4;
         rstemp = instructionlist.get(i).substring(5, 7);
         rttemp = instructionlist.get(i).substring(9, 11);

         if (rstemp.contains(",")) {
         rstemp = rstemp.substring(0, 1);
         }
         if (rttemp.contains(",")) {
         rttemp = rttemp.substring(0, 1);
         }
         rs = Integer.valueOf(rstemp);
         rt = Integer.valueOf(rttemp);
         }

         opcodebin = Integer.toBinaryString(opcode);
         if (opcodebin.length() != 6) {
         temp = "";
         for (int k = 0; k < 6 - opcodebin.length(); k++) {
         temp = temp + "0";
         }
         opcodebin = temp + opcodebin;
         }

         rsbin = Integer.toBinaryString(rs);
         if (rsbin.length() != 5) {
         temp = "";
         for (int k = 0; k < 5 - rsbin.length(); k++) {
         temp = temp + "0";
         }
         rsbin = temp + rsbin;
         }
         rtbin = Integer.toBinaryString(rt);
         if (rtbin.length() != 5) {
         temp = "";
         for (int k = 0; k < 5 - rtbin.length(); k++) {
         temp = temp + "0";
         }
         rtbin = temp + rtbin;
         }

         pcBin = Integer.toBinaryString(temppc);
         if (pcBin.length() != 16) {
         temp = "";
         for (int k = 0; k < 16 - pcBin.length(); k++) {
         temp = temp + "0";
         }
         pcBin = temp + pcBin;
         }

         //address in hex
         addresshex = new BigInteger(addressbin, 2).toString(16);
         if (addresshex.length() != 8) {
         temp = "";
         for (int m = 0; m < 8 - addresshex.length(); m++) {
         temp = temp + "0";
         }
         addresshex = temp + addresshex;
         //String jumpTo = jTextField1.getText();
         //address in binary
         addressbin = opcodebin + rsbin + rtbin + pcBin;
         }
         addressbin = opcodebin + rsbin + rtbin + pcBin;

         System.out.println(addressbin);
         opcodelist.set(i, addressbin);
         }
         }
         }
         }
         */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jLabel21.setText("");
        jLabel18.setText("");
        opcodelist.clear();
        labellist.clear();
        instructionlist.clear();
        pclist.clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
